
platform :ios, '13.0'
target 'Flash Chat iOS13' do
 # Pods for Flash Chat iOS13
  use_frameworks!
  pod 'CLTypingLabel', '~> 0.4'
  pod 'FirebaseAuth'
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
end
