
platform :ios, '13.0'
target 'Flash Chat iOS13' do
 # Pods for Flash Chat iOS13
  use_frameworks!
  pod 'CLTypingLabel', '~> 0.4'
  pod 'FirebaseAuth'
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'GoogleSignIn', '7.1.0-fac-eap-1.0.0'
  pod 'IQKeyboardManagerSwift', '~> 7.0'
end
